### ISSUE TITLE
[REFACTOR] 중복된 코드 처리 및 주석 추가

### ISSUE THREAD

**Issue by Sungah-Yoon** [KHU-Cloud-Project/Ameet-Server#38]
## ✨ 이슈 내용
> 중복성이 높은 코드 공통 메서드로 추출

## 💡 작업 내용
- [x] MeetingService 내, 회의 참석자 리스트 반환 코드 공통 메서드로 추출
- [x] 불필요한 DTO 제거
- [x] 코드에 주석 달기
- [x] warnings 제거

## 📌 참고 사항
MeetingSerivce 공통 메서드 추출 방법 아래 두 가지 중 선택 예정
- userTeamService method로 구현
- MeetingSerivce 내에 private method로 구현

**Comment by SuminSSon** [comment]
MeetingSerivce 내에 private method로 구현하는 방법 좋습니다!
